name             'windows_activedirectory'
maintainer       'Todd Pigram'
maintainer_email 'todd@toddpigram.com'
license          'Apache 2.0'
description      'Installs/Configures windows_activedirectory'
long_description 'Installs/Configures windows_activedirectory'
version          '0.2.16'
depends          'windows'
depends          'powershell'
depends          'windows_ad'